### ISSUE TITLE
Supported architectures?

### ISSUE THREAD

**Issue by katanacrimson** [cytopia/docker-ansible-lint#24]
Running into an odd failure when trying to use this docker image, but I suspect it's because I'm using the `arm32v7` architecture.

Could you possibly document what architectures are supported for this docker image on dockerhub/in the README?

**Comment by cytopia** [comment]
@damianb currently only `linux/amd64` is supported. If it is easily possible, I can also provide other flavours. Any idea how I would build an arm version?

**Comment by katanacrimson** [comment]
Probably would need a builder node that is arm32v7, or play with the experimental cross-compiling that docker introduced earlier this year: https://www.docker.com/blog/multi-arch-images/

I myself will end up going the former route, since my pi4's are already setup for gitlab-ci and have docker-dind builds going.  Figured it'd be good to ask for the architecture to be stated though, for those who follow a similar path.
